In [2]:
import numpy as np

In [38]:
n = 6
np.zeros( (3, 2*(n - 1), n//2, 2) ).shape

(3, 10, 3, 2)

In [56]:
import numpy as np
from tabulate import tabulate

# Create an example array with shape (3, 10, 5, 2)
example_array = np.zeros( (3, 10, 5, 2), dtype=int )

# Convert the last dimension to strings and concatenate
formatted_array = np.apply_along_axis(lambda x: ' vs '.join(map(str, x)), 3, example_array)

# Print the formatted array using tabulate
for i in range(formatted_array.shape[0]):
    print(f"Block {i + 1}:")
    print(tabulate(formatted_array[i], tablefmt="grid"))
    print("\n")

Block 1:
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+


Bl

In [74]:
test = np.array([
  [ 
      [ [0,1],[0,0],[0,0] ], 
      [ [0,2],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,3],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ] 
  ],
  [ 
      [ [0,0],[0,0],[0,0] ], 
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ] 
  ],
  [ 
      [ [0,0],[0,0],[0,0] ], 
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ],
      [ [0,0],[0,0],[0,0] ] 
  ]
])

# [pW[1] for pW in np.argwhere( (test == [0,0]).all(axis=3) ) if pW[2] == 0 and pW[0] == 0]

test[0, 0, 0] = [1, 0]

test[0, 0, 0]

array([1, 0])

In [84]:
type(np.float64(13) //2)

numpy.float64

In [86]:
from collections import Counter

# Initial list
days = ['Mon', 'Fri', 'Sat']

# Create a counter for the initial list
day_counts = Counter(days)

# Ensure each day appears four times
target_count = 4
result = days + [day for day in day_counts for _ in range(target_count - day_counts[day])]

print(result)

['Mon', 'Fri', 'Sat', 'Mon', 'Mon', 'Mon', 'Fri', 'Fri', 'Fri', 'Sat', 'Sat', 'Sat']


In [143]:
import numpy as np

test = np.array([
    [
        [-1, 2, 3, 4], 
        [6, -1, 7, 3],
        [6, 3, -1, 3],
        [6, 3, 9, -1]
    ],
    [
        [-1, 2, 3, 4], 
        [6, -1, 7, 3],
        [6, 3, -1, 3],
        [6, 3, 9, -1]
    ]
])

-1 in test[0, 0]

True

In [9]:
        while len(self.allMatches) != 0:
            idxMaxMatches = self.p.argsort()[::-1]
            idxMaxMatch = idxMaxMatches[0]

            weekDay, t1, t2 = np.unravel_index(idxMaxMatch, (3, self.n, self.n))
            print(weekDay, t1, t2)

            if weekDay == 0:
                freeWeeks = [pW[1] for pW in np.argwhere( (self.solution == [0,0]).any(axis=2) ) if pW[0] == weekDay and pW[2] == 0]
            else:                
                freeWeeks = [pW[1] for pW in np.argwhere( (self.solution == [0,0]).any(axis=2) ) if pW[0] != weekDay]

            for week in freeWeeks:
                
                if (t1 in self.solution[weekDay, week]) or (t2 in self.solution[weekDay, week]):
                    continue

                bestGreedyWeek = week

# 
            self.solution[weekDay, bestGreedyWeek, 0] = [t1+1, t2+1]
            self.p[idxMaxMatch] = -1
            self.allMatches.discard((t1+1, t2+1))
            
            print_solution(0, self.solution)

List time: 3.801514 seconds
Deque time: 2.575721 seconds
NumPy time: 3.520673 seconds


In [62]:
def get_incomplete_weeks(solution, n):
    incomplete_weeks = []
    allTeams = set(range(1,n+1))
    for idx_week, week in enumerate(solution.transpose(1,0,2,3)):
        idx_teams = np.where(week.flatten() != 0)
        teams = set(week.flatten()[idx_teams])
        if not allTeams.issubset(teams):
            incomplete_weeks.append(idx_week)

    return incomplete_weeks

# Beispielaufruf
n_teams = 6  # Anzahl der Teams
n_weeks = 10  # Anzahl der Wochen
t = 2  # Maximal 2 Spiele pro Freitag/Samstag
solution = np.zeros((3, n_weeks, t, 2), dtype=int)

# Beispiel: In Woche 0 spielen die Teams 1 und 5 gegeneinander am Montag
solution[0, 0, 0] = [1, 5]
solution[0, 0, 0] = [2, 4]
solution[0, 1, 1] = [3, 6]
solution[0, 2, 1] = [3, 6]

# Unvollständige Wochen und freie Tage
free_days_per_week = get_incomplete_weeks(solution, n_teams)
# free_days_per_week.keys()
# free_days_per_week.values()
free_days_per_week


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
def fill_incomplete_weeks(self, week, p_shape):
        possible_matches = self.get_teams_not_playing(week)
        print(list(possible_matches))

        matches_with_profits = self.get_profits_of_matches(week, p_shape, possible_matches)

        for t1, t2, day, match, _ in matches_with_profits:
            if self.solution[day, week, match, 0] == 0:
                self.solution[day, week, match] = [t1, t2]
                p_shape[day, t1 - 1, t2 - 1] = -1

    def get_teams_not_playing(self, week):
        all_teams = set(range(1, self.n + 1))
        teams_played = {team for day in range(self.solution.shape[0])
                            for match in range(self.solution.shape[2])
                            for team in self.solution[day, week, match]
                            if team != 0}
        teams_not_played = all_teams - teams_played
        return permutations(teams_not_played, 2)
    
    def get_profits_of_matches(self, week, p_shape, possible_matches):
        profits_matches = [(p_shape[day, t1 - 1, t2 - 1])
                        for t1, t2 in possible_matches
                        for day in range(0, 2)  # Freitag und Samstag
                        for match in range(self.solution.shape[2])
                        if self.solution[day, week, match, 0] == 0]
        
        return profits_matches

    def get_incomplete_weeks(self):
        free_days_per_week = dict()
        for idx_week in range(self.solution.shape[1]):            
            for idx_day, day in enumerate(self.solution[:, idx_week, :, :]):
                for idx_match, match in enumerate(day):
                    if not np.all(match == [0,0]):
                        continue
                    if idx_match >= 1 and idx_day == 0:
                        continue
                    free_days_per_week[idx_week] = idx_day
        print(free_days_per_week)

0

In [69]:
import timeit
from collections import deque
import numpy as np

# Parameters
num_elements = 1_000_000

# Using Python list
def using_list():
    lst = []
    for i in range(num_elements):
        lst.append(i)
    return lst

# Using deque
def using_deque():
    d = deque()
    for i in range(num_elements):
        d.append(i)
    return d

# Using preallocated NumPy array
def using_numpy():
    arr = np.zeros(num_elements, dtype=int)
    for i in range(num_elements):
        arr[i] = i
    return arr

def using_set():
    arr = set()
    for i in range(num_elements):
        arr.add(i)
    return arr

# Measure the time taken for each method
list_time = timeit.timeit(using_list, number=10)
deque_time = timeit.timeit(using_deque, number=10)
numpy_time = timeit.timeit(using_numpy, number=10)
set_time = timeit.timeit(using_set, number=10)

print(f"List time: {list_time:.6f} seconds")
print(f"Deque time: {deque_time:.6f} seconds")
print(f"NumPy time: {numpy_time:.6f} seconds")
print(f"Set time: {set_time:.6f} seconds")


List time: 0.361554 seconds
Deque time: 0.250140 seconds
NumPy time: 0.341695 seconds
Set time: 0.460969 seconds


In [92]:
import timeit
from collections import deque
import numpy as np

# Parameters
num_elements = 30_000

# Using Python list
def using_list():
    lst = list(range(num_elements))
    for i in range(num_elements):
        lst.remove(i)
    return lst

# Using deque
def using_deque():
    d = deque(range(num_elements))
    for i in range(num_elements):
        d.remove(i)
    return np.array(d)

# Using preallocated NumPy array
def using_numpy():
    arr = np.array(range(num_elements), dtype=int)
    for i in range(num_elements):
        arr[i] = 0
    return arr

def using_set():
    arr = set(range(num_elements))
    for i in range(num_elements):
        arr.remove(i)
    return arr

# Measure the time taken for each method
list_time = timeit.timeit(using_list, number=10)
deque_time = timeit.timeit(using_deque, number=10)
numpy_time = timeit.timeit(using_numpy, number=10)
set_time = timeit.timeit(using_set, number=10)

print(f"List time: {list_time:.6f} seconds")
print(f"Deque time: {deque_time:.6f} seconds")
print(f"NumPy time: {numpy_time:.6f} seconds")
print(f"Set time: {set_time:.6f} seconds")


List time: 6.917812 seconds
Deque time: 0.009854 seconds
NumPy time: 0.017011 seconds
Set time: 0.010244 seconds


In [91]:
import numpy as np

# Define the initial array
array = np.array([
    [0, 1], [0, 2], [0, 3],
    [1, 0], [1, 1], [1, 2], [1, 3],
    [2, 0], [2, 1], [2, 2], [2, 3]
])

# Define the rows to remove
rows_to_remove = [[0, 1], [0, 2], [0, 3]]

# Filter out the rows
filtered_array = np.array([row for row in array if list(row) not in rows_to_remove])

print(filtered_array)


[[1 0]
 [1 1]
 [1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]]


In [53]:
import numpy as np
idx = [ 8, 18, 12, 11,  2,  0, 21, 20, 10, 13, 19,  6,  3, 16, 23, 22,  9,  1, 17,  7,  5,  4, 14, 15] 
remove = [ 0,  1,  4,  5,  8,  9, 10, 11, 12, 13]

np.setdiff1d(idx, remove, assume_unique=True)

array([18,  2, 21, 20, 19,  6,  3, 16, 23, 22, 17,  7, 14, 15])