In [5]:
import numpy as np

In [38]:
n = 6
np.zeros( (3, 2*(n - 1), n//2, 2) ).shape

(3, 10, 3, 2)

In [56]:
import numpy as np
from tabulate import tabulate

# Create an example array with shape (3, 10, 5, 2)
example_array = np.zeros( (3, 10, 5, 2), dtype=int )

# Convert the last dimension to strings and concatenate
formatted_array = np.apply_along_axis(lambda x: ' vs '.join(map(str, x)), 3, example_array)

# Print the formatted array using tabulate
for i in range(formatted_array.shape[0]):
    print(f"Block {i + 1}:")
    print(tabulate(formatted_array[i], tablefmt="grid"))
    print("\n")

Block 1:
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+
| 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 | 0 vs 0 |
+--------+--------+--------+--------+--------+


Bl

In [86]:
import numpy as np
test = np.array([
    [
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ]
    ],
    [
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ]
    ],
    [
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ],
        [ [0,0], [0,0], [0,0], [0,0] ]
    ],
    
])

test = test.transpose(1,0,2,3)


from sklearn.preprocessing import minmax_scale 
arr = np.array([123123,124515123,123141231,1,2312341512313,23232])

sum(arr / arr.sum())

0.9999999999999999

In [98]:
import numpy as np

arr = np.array([
    [[1,2], [3,4], [5,6], [np.nan, np.nan]],
    [[8,10], [9,11], [7,12], [np.nan, np.nan]]
])

Vorher:
[[[0.48006285 0.60599716]
  [0.54061589 0.73366835]
  [0.78541137 0.9871337 ]
  [0.52550028 0.28252382]]

 [[0.54852085 0.55906417]
  [0.14436845 0.60444322]
  [0.20047513 0.33880522]
  [0.91942461 0.02280469]]

 [[0.09345171 0.45857952]
  [0.85042219 0.91520917]
  [0.78109169 0.68444682]
  [0.05097197 0.52081283]]]

Nachher:
[[[0.48006285 0.60599716]
  [0.54061589 0.73366835]
  [0.78541137 0.9871337 ]
  [0.52550028 0.28252382]]

 [[0.91942461 0.02280469]
  [0.14436845 0.60444322]
  [0.54852085 0.55906417]
  [0.20047513 0.33880522]]

 [[0.78109169 0.68444682]
  [0.05097197 0.52081283]
  [0.85042219 0.91520917]
  [0.09345171 0.45857952]]]
